### ISSUE TITLE
chainer version is not right？

### ISSUE THREAD

**Issue by mstc-xqp** [kunglab/branchynet#2]
File "/usr/lib/python2.7/site-packages/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
TypeError: forward() takes exactly 2 arguments (3 given)

**Comment by mstc-xqp** [comment]
I use chainer 5.0,while it is written is chainer 1.90 or 3.0?

**Comment by Gxllii** [comment]
> I use chainer 5.0,while it is written is chainer 1.90 or 3.0?

Chainer 1.10.0 is OK.

**Comment by LynsherLiu** [comment]
The chainer version 1.10.0 requires cuda and cudnn environment, but I don't have a NIVIDA gpu and just want to use default cpu so I installed chainer 3.0.0.
I tried to use chainer 3.0.0 or 5.0.0 to run, but there are some error: ValueError: train argument is not supported anymore. Use chainer.using_config. I guess these arguments are used only in chainer version 1, right? So I'm in a deadlock?

**Comment by mstc-xqp** [comment]
> > I use chainer 5.0,while it is written is chainer 1.90 or 3.0?
> 
> Chainer 1.10.0 is OK.
请问你有用cupy吗你用哪个版本呢，你有复现出来吗 ，请问可以加一下微信交流吗，我微信是a409197863

我用CPU版本跑了mnist 要一天，模型能出来，就是可视化那里报错

Traceback (most recent call last):
  File "experiment_lenet_mnist.py", line 129, in <module>
    title='LeNet CPU', output_path='_figs/lenet_cpu.pdf')
  File "/home/xqp/Desktop/branchynet-master/branchynet/visualize.py", line 103, in plot_line_tradeoff
    'figure.figsize': [4.5, 3.5]})
  File "/usr/lib/python2.7/_abcoll.py", line 566, in update
    self[key] = other[key]
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 929, in __setitem__
    'list of valid parameters.' % (key,))
KeyError: 'text.fontsize is not a valid rc parameter. See rcParams.keys() for a list of valid parameters.'
